apiVersion: v1
kind: Namespace
metadata:
  name: agent-rt-sandbox-system
  labels:
    agent-rt.nvidia.com/sandbox-service: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
---
apiVersion: v1
kind: Namespace
metadata:
  name: agent-sandboxes
  labels:
    agent-rt.nvidia.com/sandbox-tenant: "true"
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
