apiVersion: v1
kind: Service
metadata:
  name: agent-rt-sandbox-service
  namespace: agent-rt-sandbox-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: agent-rt-sandbox-service
  ports:
    - name: http
      port: 8090
      targetPort: http
      protocol: TCP
